#IP of the Kubernetes controller node
[k8s_controller]
10.100.75.16
#IsP of the Kubernetes worker node
[k8s_workers]
10.100.75.17
10.100.75.18

[k8s_nodes:children]
k8s_controller
k8s_workers

#username to connect to the nodes
[k8s_nodes:vars]
ansible_user=user
